# Generated by Django 2.2.6 on 2019-11-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
    ]
