# Generated by Django 2.2.6 on 2019-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191101_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
